### PR TITLE
Use cross-platform startfile equivalent

### PR DESCRIPTION
**Pull request by Sprixitite**
To fix one of the things limiting Linux compatibility as mentioned in #18

### CODE REVIEW

**Comment by Wolfmyths** [comment]
@Sprixitite 
So I went to check out `sys.platform`'s possible return values and it seems like neither of those return values are there as seen here

https://docs.python.org/3.11/library/sys.html#sys.platform

I've never owned a Linux system so I don't understand how the command prompt can differ from using `darwin` or `xdg-open`

Check out `os.uname()` as well

https://docs.python.org/3.11/library/os.html#os.uname

Also one more thing, for consistency's sake, make a constant variable in `constant_vars.py` of the platform because we will probably use this variable across the program.

**Comment by Sprixitite** [comment]
The system.platform usage is valid, having both tested locally, and taken the time to double check I knew what was going on because it's written using some pythonic ternary operator I think is causing you (and initially caused me) some confusion

The code first checks if we're on win32, if so it uses os.startfile like before

If not it then checks if we're on apple ("Darwin"), and if so it sets the "opener" variable to "open" (I don't use apple products but apparently this command line API does what we want), if we're not on apple, it assumes we're on a Linux distro which supports X11 APIs, and assigns "opener" to "xdg-open", the correct command line API for linux

I'm currently about to go to bed, so I can rectify the issue with constants when I get time tomorrow, but the file open dialogue should work fine

(P.S: This is why I hate pythons syntax, it causes confusion like this)

**Comment by Sprixitite** [comment]
I'm aware apple support is unnecessary ATM, but it's practically free and could come in useful later if you decide to use this for Mac supported games

**Comment by Sprixitite** [comment]
Sorry for leaving this open for so long, life's been getting in the way and between forgetting I opened this PR and everything else I've not found the time to do anything I've mentioned, I'll try and get this moved along at some point ASAP, thanks for your patience

**Comment by Wolfmyths** [comment]
It's okay! Things happen.

**Comment by Wolfmyths** [comment]
Hey I'm gonna close this because I've gotten a hold of a virtual machine and started testing this app on Mint and worked on some of this, of course your welcome to improve the changes I've made to add better compatibility since this is my first time using Linux.

If you are still interested take a look at the latest commits to the [future-update](https://github.com/Wolfmyths/Myth-Mod-Manager/tree/future-update) branch

**Pull request closed without merging**
