### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Trivoz**
### Changes
* Minor changes to the constants file.
* Tidies up comments a tiny bit

### CODE REVIEW

**Comment by Wolfmyths** [comment]
The reason why `MODSIGNORE` is a tuple is because it contains a list of folder names used in PAYDAY 2's community mod library and API, `BeardLib`.

Without it, these folders which are not mods would show up as a mod in the program.

I haven't used sets before so my knowledge is very limited with them. But unless I am missing something, there is no point in making `MODSIGNORE` into a set.

The times `MODSIGNORE` is used is when checking if a folder in `/mods/` is one of these folders.

**Comment by JoshuaDRose** [comment]
> The reason why `MODSIGNORE` is a tuple is because it contains a list of folder names used in PAYDAY 2's community mod library and API, `BeardLib`.
> 
> Without it, these folders which are not mods would show up as a mod in the program.
> 
> I haven't used sets before so my knowledge is very limited with them. But unless I am missing something, there is no point in making `MODSIGNORE` into a set.
> 
> The times `MODSIGNORE` is used is when checking if a folder in `/mods/` is one of these folders.

Got it, thanks for clearing that up.

**Review by JoshuaDRose — COMMENTED** [review]
to be approved

**Review by Wolfmyths — CHANGES_REQUESTED** [review]
So far it looks good.

Just to double check though, compare these changes with the 1.0.0-release branch because some code has been changed due to the support of rar and 7z extensions. And possibly some other small changes.

For an example, the code you changed in lines 81-93 has been altered to also accept rar and 7z files as "zip" in the 1.0.0-release branch.

Sorry about the confusion I'm still figuring out how I should document for contributors.

**Comment by Wolfmyths** [comment]
This PR has been up for a while and most of the improvements are no longer needed

**Pull request closed without merging**
